STAT BALANCE = 500
STAT PASSMONEY = 0
STAT DONTPASSMONEY = 0  
STAT COMEMONEY = 0
STAT DONTCOMEMONEY = 0
STAT TRUE = 1
STAT ROLLOOP = 0
RESPAWN-WHILE(TRUE == 1){
	STAT ROLLOOP = 0
	DETECTION-METER |"CRAPS GAME" "->" "--------------" "->" "1. PASS" "->" "2. DONT PASS" "->" "3. ROLL" "->"|
	DETECTION-METER |"BALANCE: " BALANCE "->" |
	ENTER-QUEST pChoice
	SHOOT-IF(pChoice == 1){
		DETECTION-METER |"BET MENU: " "->"|
		DETECTION-METER |"1. 100 " "->"|
		DETECTION-METER |"2. 200 " "->"|
		ENTER-QUEST pChoice
		SHOOT-IF(pChoice == 1){
			SHOOT-IF(BALANCE == 0){
				DETECTION-METER |"INVALID BALANCE" "->"|
				DESPAWN GAME
			}
			STAT BALANCE = BALANCE + -100
			STAT PASSMONEY = PASSMONEY + 100 
		}
		SHOOT-IF(pChoice == 2){
			SHOOT-IF(BALANCE == 100){
				DETECTION-METER |"INVALID BALANCE" "->" |
				DESPAWN GAME
			}
			SHOOT-IF(BALANCE == 0){
				DETECTION-METER |"INVALID BALANCE" "->" |
				DESPAWN GAME
			}
			STAT BALANCE = BALANCE + -200
			STAT PASSMONEY = PASSMONEY + 100
		} 
		STAT pChoice = 0
	}
	SHOOT-IF(pChoice == 2){
		DETECTION-METER |"BET MENU: " "->"|
		DETECTION-METER |"1. 100 " "->"|
		DETECTION-METER |"2. 200 " "->"|
		ENTER-QUEST pChoice
		SHOOT-IF(pChoice == 1){
			SHOOT-IF(BALANCE == 0){
				DETECTION-METER |"BALANCE: " BALANCE "->" |
				DESPAWN GAME
			}
			STAT BALANCE = BALANCE + -100
			STAT DONTPASSMONEY = DONTPASSMONEY + 100 
		}
		SHOOT-IF(pChoice == 2){
			SHOOT-IF(BALANCE == 100){
				DETECTION-METER |"INVALID BALANCE" "->" |
				DESPAWN GAME
			}
			SHOOT-IF(BALANCE == 0){
				DETECTION-METER |"INVALID BALANCE" "->" |
				DESPAWN GAME
			}
			STAT BALANCE = BALANCE + -200
			STAT DONTPASSMONEY = DONTPASSMONEY + 100
		} 
			STAT pChoice = 0
	}
	SHOOT-IF(pChoice == 3){
		RESPAWN-WHILE(ROLLOOP == 0){
			STAT DIE1 = ROLL
			STAT DIE2 = ROLL
			STAT DICE = DIE1 + DIE2
			DETECTION-METER |"DICE: " DICE "->"|
			SHOOT-IF(DICE == 2){
				DETECTION-METER |"DONTPASS WINS" "->"|
				STAT BALANCE = BALANCE + DONTPASSMONEY * 2 
				STAT PASSMONEY = 0
				STAT DONTPASSMONEY = 0
				STAT pChoice = 0
				STAT ROLLOOP = 1
			}
			SHOOT-IF(DICE == 3){
				DETECTION-METER |"DONTPASS WINS" "->"|
				STAT BALANCE = BALANCE + DONTPASSMONEY * 2
				STAT PASSMONEY = 0
				STAT DONTPASSMONEY = 0
				STAT pChoice = 0
				STAT ROLLOOP = 1
			}
			SHOOT-IF(DICE == 7){
				DETECTION-METER |"PASS WINS" "->"|
				STAT BALANCE = BALANCE + PASSMONEY * 2
				STAT PASSMONEY = 0
				STAT DONTPASSMONEY = 0
				STAT pChoice = 0
				STAT ROLLOOP = 1
			}
			SHOOT-IF(DICE == 11){
				DETECTION-METER |"PASS WINS" "->"|
				STAT BALANCE = BALANCE + PASSMONEY * 2
				STAT PASSMONEY = 0
				STAT DONTPASSMONEY = 0
				STAT pChoice = 0
				STAT ROLLOOP = 1
			}
			SHOOT-IF(DICE == 12){
				DETECTION-METER |"DONTPASS WINS" "->"|
				STAT BALANCE = BALANCE + DONTPASSMONEY * 2
				STAT PASSMONEY = 0
				STAT DONTPASSMONEY = 0
				STAT pChoice = 0
				STAT ROLLOOP = 1
			}
			SHOOT-IF(ROLLOOP == 0){
				DETECTION-METER |"CRAPS GAME" "->" "--------------" "->" "1. COME" "->" "2. DONT COME" "->" "3. ROLL" "->"|
				DETECTION-METER |"BALANCE: " BALANCE "->" |
				ENTER-QUEST pChoice
				SHOOT-IF(pChoice == 1){
					DETECTION-METER |"BET MENU: " "->"|
					DETECTION-METER |"1. 100 " "->"|
					DETECTION-METER |"2. 200 " "->"|
					ENTER-QUEST pChoice
					SHOOT-IF(pChoice == 1){
						SHOOT-IF(BALANCE == 0){
							DETECTION-METER |"INVALID BALANCE" "->"|
							DESPAWN GAME
						}
						STAT BALANCE = BALANCE + -100
						STAT PASSMONEY = PASSMONEY + 100 
					}
					SHOOT-IF(pChoice == 2){
						SHOOT-IF(BALANCE == 100){
							DETECTION-METER |"INVALID BALANCE" "->" |
							DESPAWN GAME
						}
						SHOOT-IF(BALANCE == 0){
							DETECTION-METER |"INVALID BALANCE" "->" |
							DESPAWN GAME
						}
						STAT BALANCE = BALANCE + -200
						STAT PASSMONEY = PASSMONEY + 100
					} 
				STAT pChoice = 0
				}
				SHOOT-IF(pChoice == 2){
					DETECTION-METER |"BET MENU: " "->"|
					DETECTION-METER |"1. 100 " "->"|
					DETECTION-METER |"2. 200 " "->"|
					ENTER-QUEST pChoice
					SHOOT-IF(pChoice == 1){
						SHOOT-IF(BALANCE == 0){
							DETECTION-METER |"BALANCE: " BALANCE "->" |
							DESPAWN GAME
						}
						STAT BALANCE = BALANCE + -100
						STAT DONTPASSMONEY = DONTPASSMONEY + 100 
					}
					SHOOT-IF(pChoice == 2){
						SHOOT-IF(BALANCE == 100){
							DETECTION-METER |"INVALID BALANCE" "->" |
							DESPAWN GAME
						}
						SHOOT-IF(BALANCE == 0){
							DETECTION-METER |"INVALID BALANCE" "->" |
							DESPAWN GAME
						}
						STAT BALANCE = BALANCE + -200
						STAT DONTPASSMONEY = DONTPASSMONEY + 100
					} 
				STAT pChoice = 0
				}
			}
		}	
	}
}